name: Check docstrings
on:
  workflow_dispatch:
    push:
      branches:
        - gh-pages
jobs:
  check-cells:
    runs-on: ubuntu-latest
    steps: make test
      - name: doctest
        run: make test
